### ISSUE TITLE
search_series

### ISSUE THREAD

**Issue by tyl0re** [kodi-community-addons/script.module.thetvdb#6]
Searching Series with other Language Name doens't work with Kodi=English

title="Alles was zählt"
tvdb.search_series(title,prefer_localized=True)

Setting the Interface too German does work. I think similiar Problem would exist between other languages

**Comment by marcelveldt** [comment]
This is true because in German each title gets a localised title. So the same movie or series will be named differently in german or English.

Note:
If you search for the original English title while having the language set to German, you will get the german alternative as result. The same applies off course if you search for the german title.

If you search for the german title while having the language set to English you will most probably not get any result because of the filtering that is applied.

**Comment by tyl0re** [comment]
Thanks, the Problem is an Liste with German Series like "Alles was zählt" and English only Series. 
So switching the Laguage  in the Plugin would solv the Problem

**Comment by tyl0re** [comment]
Im Closing it since it would be resolved with the Language Improvment
